version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dharani2d@
      POSTGRES_DB: event
