version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8181:8181"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/myappdb
      - SPRING_DATASOURCE_USERNAME=myappuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=myappdb
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
